// 150 Questions across 10 dimensions for Friendship Health Assessment
export const DIMENSIONS = [
  { id: 'trust', name: 'Trust & Reliability', nameTanglish: 'Nambikaiyum Ethirpaarpum', icon: '🤝' },
  { id: 'communication', name: 'Communication', nameTanglish: 'Pesarathu', icon: '💬' },
  { id: 'support', name: 'Emotional Support', nameTanglish: 'Manathin Aathara', icon: '❤️' },
  { id: 'respect', name: 'Mutual Respect', nameTanglish: 'Mariyathai', icon: '🙏' },
  { id: 'boundaries', name: 'Boundaries', nameTanglish: 'Ellai', icon: '🛡️' },
  { id: 'growth', name: 'Personal Growth', nameTanglish: 'Valarchi', icon: '🌱' },
  { id: 'fun', name: 'Fun & Enjoyment', nameTanglish: 'Sandhosham', icon: '🎉' },
  { id: 'conflict', name: 'Conflict Resolution', nameTanglish: 'Prachana Theervu', icon: '⚖️' },
  { id: 'loyalty', name: 'Loyalty', nameTanglish: 'Thanimaiyum Nilaiyum', icon: '🔒' },
  { id: 'authenticity', name: 'Authenticity', nameTanglish: 'Nijamana Thamai', icon: '✨' }
];

// Helper function to get dimension name based on language
export const getDimensionName = (dimension, language = 'english') => {
  if (language === 'tanglish') {
    return dimension.nameTanglish || dimension.name;
  }
  return dimension.name;
};

export const QUESTIONS = {
  english: [
    // Trust & Reliability (15 questions)
    { id: 1, dimension: 'trust', direction: 'them', text: 'My friend keeps their promises to me' },
    { id: 2, dimension: 'trust', direction: 'me', text: 'I consistently follow through on commitments I make to my friend' },
    { id: 3, dimension: 'trust', direction: 'them', text: 'I can confide in my friend without fear of judgment' },
    { id: 4, dimension: 'trust', direction: 'me', text: 'I keep my friend\'s secrets safe' },
    { id: 5, dimension: 'trust', direction: 'them', text: 'My friend is honest with me, even when it\'s difficult' },
    { id: 6, dimension: 'trust', direction: 'me', text: 'I am truthful with my friend, even about uncomfortable topics' },
    { id: 7, dimension: 'trust', direction: 'them', text: 'My friend shows up when they say they will' },
    { id: 8, dimension: 'trust', direction: 'me', text: 'I am reliable when my friend needs me' },
    { id: 9, dimension: 'trust', direction: 'them', text: 'I trust my friend with important information about my life' },
    { id: 10, dimension: 'trust', direction: 'me', text: 'I handle my friend\'s personal information responsibly' },
    { id: 11, dimension: 'trust', direction: 'them', text: 'My friend admits when they make mistakes' },
    { id: 12, dimension: 'trust', direction: 'me', text: 'I take accountability for my errors in our friendship' },
    { id: 13, dimension: 'trust', direction: 'them', text: 'My friend doesn\'t gossip about me to others' },
    { id: 14, dimension: 'trust', direction: 'me', text: 'I speak positively about my friend when they\'re not around' },
    { id: 15, dimension: 'trust', direction: 'them', text: 'I feel secure in this friendship' },

    // Communication (15 questions)
    { id: 16, dimension: 'communication', direction: 'them', text: 'My friend listens actively when I speak' },
    { id: 17, dimension: 'communication', direction: 'me', text: 'I give my friend my full attention during conversations' },
    { id: 18, dimension: 'communication', direction: 'them', text: 'My friend asks follow-up questions showing genuine interest' },
    { id: 19, dimension: 'communication', direction: 'me', text: 'I ask thoughtful questions about my friend\'s life' },
    { id: 20, dimension: 'communication', direction: 'them', text: 'My friend communicates clearly and directly' },
    { id: 21, dimension: 'communication', direction: 'me', text: 'I express my thoughts and feelings clearly to my friend' },
    { id: 22, dimension: 'communication', direction: 'them', text: 'My friend responds to my messages in a reasonable time' },
    { id: 23, dimension: 'communication', direction: 'me', text: 'I reply to my friend\'s messages promptly' },
    { id: 24, dimension: 'communication', direction: 'them', text: 'My friend shares important updates from their life' },
    { id: 25, dimension: 'communication', direction: 'me', text: 'I keep my friend informed about significant events in my life' },
    { id: 26, dimension: 'communication', direction: 'them', text: 'My friend is comfortable discussing difficult topics' },
    { id: 27, dimension: 'communication', direction: 'me', text: 'I can talk to my friend about challenging subjects' },
    { id: 28, dimension: 'communication', direction: 'them', text: 'My friend remembers details from our conversations' },
    { id: 29, dimension: 'communication', direction: 'me', text: 'I remember important things my friend tells me' },
    { id: 30, dimension: 'communication', direction: 'them', text: 'Communication feels natural and easy with my friend' },

    // Emotional Support (15 questions)
    { id: 31, dimension: 'support', direction: 'them', text: 'My friend is there for me during difficult times' },
    { id: 32, dimension: 'support', direction: 'me', text: 'I provide support when my friend is struggling' },
    { id: 33, dimension: 'support', direction: 'them', text: 'My friend validates my feelings' },
    { id: 34, dimension: 'support', direction: 'me', text: 'I acknowledge and validate my friend\'s emotions' },
    { id: 35, dimension: 'support', direction: 'them', text: 'My friend celebrates my successes and achievements' },
    { id: 36, dimension: 'support', direction: 'me', text: 'I genuinely celebrate my friend\'s accomplishments' },
    { id: 37, dimension: 'support', direction: 'them', text: 'My friend offers comfort when I\'m upset' },
    { id: 38, dimension: 'support', direction: 'me', text: 'I provide emotional comfort to my friend when needed' },
    { id: 39, dimension: 'support', direction: 'them', text: 'My friend encourages me during challenges' },
    { id: 40, dimension: 'support', direction: 'me', text: 'I motivate and encourage my friend' },
    { id: 41, dimension: 'support', direction: 'them', text: 'My friend shows empathy for my struggles' },
    { id: 42, dimension: 'support', direction: 'me', text: 'I empathize with my friend\'s difficulties' },
    { id: 43, dimension: 'support', direction: 'them', text: 'My friend checks in on me regularly' },
    { id: 44, dimension: 'support', direction: 'me', text: 'I reach out to see how my friend is doing' },
    { id: 45, dimension: 'support', direction: 'them', text: 'I feel emotionally safe with my friend' },

    // Mutual Respect (15 questions)
    { id: 46, dimension: 'respect', direction: 'them', text: 'My friend respects my opinions, even when we disagree' },
    { id: 47, dimension: 'respect', direction: 'me', text: 'I respect my friend\'s viewpoints, even if different from mine' },
    { id: 48, dimension: 'respect', direction: 'them', text: 'My friend values my time' },
    { id: 49, dimension: 'respect', direction: 'me', text: 'I am considerate of my friend\'s schedule and commitments' },
    { id: 50, dimension: 'respect', direction: 'them', text: 'My friend accepts me as I am' },
    { id: 51, dimension: 'respect', direction: 'me', text: 'I accept my friend without trying to change them' },
    { id: 52, dimension: 'respect', direction: 'them', text: 'My friend respects my life choices' },
    { id: 53, dimension: 'respect', direction: 'me', text: 'I support my friend\'s decisions and life path' },
    { id: 54, dimension: 'respect', direction: 'them', text: 'My friend doesn\'t belittle or mock me' },
    { id: 55, dimension: 'respect', direction: 'me', text: 'I avoid making fun of my friend in hurtful ways' },
    { id: 56, dimension: 'respect', direction: 'them', text: 'My friend treats me as an equal' },
    { id: 57, dimension: 'respect', direction: 'me', text: 'I treat my friend as an equal partner in the friendship' },
    { id: 58, dimension: 'respect', direction: 'them', text: 'My friend respects my privacy' },
    { id: 59, dimension: 'respect', direction: 'me', text: 'I respect my friend\'s need for privacy' },
    { id: 60, dimension: 'respect', direction: 'them', text: 'I feel valued and appreciated by my friend' },

    // Boundaries (15 questions)
    { id: 61, dimension: 'boundaries', direction: 'them', text: 'My friend respects my boundaries' },
    { id: 62, dimension: 'boundaries', direction: 'me', text: 'I honor my friend\'s boundaries' },
    { id: 63, dimension: 'boundaries', direction: 'them', text: 'My friend doesn\'t pressure me to do things I\'m uncomfortable with' },
    { id: 64, dimension: 'boundaries', direction: 'me', text: 'I don\'t push my friend beyond their comfort zone' },
    { id: 65, dimension: 'boundaries', direction: 'them', text: 'My friend understands when I need space' },
    { id: 66, dimension: 'boundaries', direction: 'me', text: 'I give my friend space when they need it' },
    { id: 67, dimension: 'boundaries', direction: 'them', text: 'My friend accepts my "no" without guilt-tripping' },
    { id: 68, dimension: 'boundaries', direction: 'me', text: 'I accept my friend\'s "no" gracefully' },
    { id: 69, dimension: 'boundaries', direction: 'them', text: 'My friend doesn\'t make excessive demands on my time' },
    { id: 70, dimension: 'boundaries', direction: 'me', text: 'I am mindful of not overwhelming my friend with demands' },
    { id: 71, dimension: 'boundaries', direction: 'them', text: 'My friend respects my other relationships' },
    { id: 72, dimension: 'boundaries', direction: 'me', text: 'I support my friend having other friendships' },
    { id: 73, dimension: 'boundaries', direction: 'them', text: 'My friend communicates their boundaries clearly' },
    { id: 74, dimension: 'boundaries', direction: 'me', text: 'I express my boundaries clearly to my friend' },
    { id: 75, dimension: 'boundaries', direction: 'them', text: 'The friendship feels balanced, not one-sided' },

    // Personal Growth (15 questions)
    { id: 76, dimension: 'growth', direction: 'them', text: 'My friend encourages my personal development' },
    { id: 77, dimension: 'growth', direction: 'me', text: 'I support my friend\'s growth and aspirations' },
    { id: 78, dimension: 'growth', direction: 'them', text: 'My friend challenges me to be better (in a positive way)' },
    { id: 79, dimension: 'growth', direction: 'me', text: 'I help my friend reach their potential' },
    { id: 80, dimension: 'growth', direction: 'them', text: 'My friend isn\'t threatened by my success' },
    { id: 81, dimension: 'growth', direction: 'me', text: 'I feel genuinely happy about my friend\'s achievements' },
    { id: 82, dimension: 'growth', direction: 'them', text: 'My friend inspires me to pursue my goals' },
    { id: 83, dimension: 'growth', direction: 'me', text: 'I encourage my friend to chase their dreams' },
    { id: 84, dimension: 'growth', direction: 'them', text: 'My friend gives constructive feedback when I ask for it' },
    { id: 85, dimension: 'growth', direction: 'me', text: 'I offer helpful advice when my friend seeks it' },
    { id: 86, dimension: 'growth', direction: 'them', text: 'My friend helps me learn from my mistakes' },
    { id: 87, dimension: 'growth', direction: 'me', text: 'I help my friend learn and grow from challenges' },
    { id: 88, dimension: 'growth', direction: 'them', text: 'I\'ve grown as a person because of this friendship' },
    { id: 89, dimension: 'growth', direction: 'me', text: 'I contribute positively to my friend\'s personal development' },
    { id: 90, dimension: 'growth', direction: 'them', text: 'My friend supports me trying new things' },

    // Fun & Enjoyment (15 questions)
    { id: 91, dimension: 'fun', direction: 'them', text: 'I genuinely enjoy spending time with my friend' },
    { id: 92, dimension: 'fun', direction: 'me', text: 'My friend seems to enjoy my company' },
    { id: 93, dimension: 'fun', direction: 'them', text: 'My friend makes me laugh' },
    { id: 94, dimension: 'fun', direction: 'me', text: 'I bring joy and laughter to my friend' },
    { id: 95, dimension: 'fun', direction: 'them', text: 'Time passes quickly when I\'m with my friend' },
    { id: 96, dimension: 'fun', direction: 'me', text: 'My friend and I create fun memories together' },
    { id: 97, dimension: 'fun', direction: 'them', text: 'My friend initiates plans to hang out' },
    { id: 98, dimension: 'fun', direction: 'me', text: 'I make an effort to spend quality time with my friend' },
    { id: 99, dimension: 'fun', direction: 'them', text: 'My friend shares my sense of humor' },
    { id: 100, dimension: 'fun', direction: 'me', text: 'I appreciate my friend\'s personality and quirks' },
    { id: 101, dimension: 'fun', direction: 'them', text: 'My friend introduces me to new experiences' },
    { id: 102, dimension: 'fun', direction: 'me', text: 'I share interesting activities with my friend' },
    { id: 103, dimension: 'fun', direction: 'them', text: 'Being with my friend reduces my stress' },
    { id: 104, dimension: 'fun', direction: 'me', text: 'My friend feels comfortable and relaxed around me' },
    { id: 105, dimension: 'fun', direction: 'them', text: 'I look forward to seeing my friend' },

    // Conflict Resolution (15 questions)
    { id: 106, dimension: 'conflict', direction: 'them', text: 'My friend addresses issues directly rather than avoiding them' },
    { id: 107, dimension: 'conflict', direction: 'me', text: 'I communicate problems rather than letting them fester' },
    { id: 108, dimension: 'conflict', direction: 'them', text: 'My friend stays calm during disagreements' },
    { id: 109, dimension: 'conflict', direction: 'me', text: 'I remain respectful even when we\'re in conflict' },
    { id: 110, dimension: 'conflict', direction: 'them', text: 'My friend apologizes sincerely when they\'re wrong' },
    { id: 111, dimension: 'conflict', direction: 'me', text: 'I offer genuine apologies when I make mistakes' },
    { id: 112, dimension: 'conflict', direction: 'them', text: 'My friend is willing to compromise' },
    { id: 113, dimension: 'conflict', direction: 'me', text: 'I look for middle ground during disagreements' },
    { id: 114, dimension: 'conflict', direction: 'them', text: 'My friend forgives and moves forward after conflicts' },
    { id: 115, dimension: 'conflict', direction: 'me', text: 'I let go of grudges and forgive my friend' },
    { id: 116, dimension: 'conflict', direction: 'them', text: 'My friend doesn\'t bring up past mistakes repeatedly' },
    { id: 117, dimension: 'conflict', direction: 'me', text: 'I don\'t hold past issues over my friend\'s head' },
    { id: 118, dimension: 'conflict', direction: 'them', text: 'My friend tries to understand my perspective during conflicts' },
    { id: 119, dimension: 'conflict', direction: 'me', text: 'I make an effort to see things from my friend\'s viewpoint' },
    { id: 120, dimension: 'conflict', direction: 'them', text: 'We resolve conflicts constructively' },

    // Loyalty (15 questions)
    { id: 121, dimension: 'loyalty', direction: 'them', text: 'My friend stands up for me when others criticize me' },
    { id: 122, dimension: 'loyalty', direction: 'me', text: 'I defend my friend when they\'re not present' },
    { id: 123, dimension: 'loyalty', direction: 'them', text: 'My friend prioritizes our friendship' },
    { id: 124, dimension: 'loyalty', direction: 'me', text: 'I make our friendship a priority in my life' },
    { id: 125, dimension: 'loyalty', direction: 'them', text: 'My friend is consistent in our friendship' },
    { id: 126, dimension: 'loyalty', direction: 'me', text: 'I am dependable and consistent as a friend' },
    { id: 127, dimension: 'loyalty', direction: 'them', text: 'My friend doesn\'t abandon me during tough times' },
    { id: 128, dimension: 'loyalty', direction: 'me', text: 'I stick by my friend through their challenges' },
    { id: 129, dimension: 'loyalty', direction: 'them', text: 'My friend includes me in their life' },
    { id: 130, dimension: 'loyalty', direction: 'me', text: 'I make an effort to include my friend in my life' },
    { id: 131, dimension: 'loyalty', direction: 'them', text: 'My friend doesn\'t cancel plans at the last minute (except for emergencies)' },
    { id: 132, dimension: 'loyalty', direction: 'me', text: 'I honor my commitments to my friend' },
    { id: 133, dimension: 'loyalty', direction: 'them', text: 'My friend has my back' },
    { id: 134, dimension: 'loyalty', direction: 'me', text: 'I support my friend unconditionally' },
    { id: 135, dimension: 'loyalty', direction: 'them', text: 'I can count on my friend long-term' },

    // Authenticity (15 questions)
    { id: 136, dimension: 'authenticity', direction: 'them', text: 'My friend is genuine and authentic with me' },
    { id: 137, dimension: 'authenticity', direction: 'me', text: 'I can be my true self around my friend' },
    { id: 138, dimension: 'authenticity', direction: 'them', text: 'My friend shares their real thoughts and feelings' },
    { id: 139, dimension: 'authenticity', direction: 'me', text: 'I express my authentic self in this friendship' },
    { id: 140, dimension: 'authenticity', direction: 'them', text: 'My friend doesn\'t pretend to be someone they\'re not' },
    { id: 141, dimension: 'authenticity', direction: 'me', text: 'I don\'t feel the need to wear a mask around my friend' },
    { id: 142, dimension: 'authenticity', direction: 'them', text: 'My friend admits their vulnerabilities' },
    { id: 143, dimension: 'authenticity', direction: 'me', text: 'I feel safe showing my vulnerable side to my friend' },
    { id: 144, dimension: 'authenticity', direction: 'them', text: 'My friend\'s words match their actions' },
    { id: 145, dimension: 'authenticity', direction: 'me', text: 'I practice what I preach in this friendship' },
    { id: 146, dimension: 'authenticity', direction: 'them', text: 'My friend doesn\'t play games or manipulate' },
    { id: 147, dimension: 'authenticity', direction: 'me', text: 'I am straightforward and honest in this friendship' },
    { id: 148, dimension: 'authenticity', direction: 'them', text: 'I trust my friend\'s intentions are genuine' },
    { id: 149, dimension: 'authenticity', direction: 'me', text: 'My friend trusts that I have their best interests at heart' },
    { id: 150, dimension: 'authenticity', direction: 'them', text: 'This friendship feels real and meaningful' },
  ],
  tanglish: [
    // Trust & Reliability (15 questions)
    { id: 1, dimension: 'trust', direction: 'them', text: 'En friend avanga vaakkula nippanga' },
    { id: 2, dimension: 'trust', direction: 'me', text: 'Naan en friend-kku kodutha vaakka-a neraivetthuven' },
    { id: 3, dimension: 'trust', direction: 'them', text: 'En friend-kitta yosikkama pesalaam' },
    { id: 4, dimension: 'trust', direction: 'me', text: 'Naan en friend-oda ragasiyam-a safe-a vechukuven' },
    { id: 5, dimension: 'trust', direction: 'them', text: 'Kashtam-na kooda en friend unmai-ya solluvanga' },
    { id: 6, dimension: 'trust', direction: 'me', text: 'Kashtamaana vishayam-na kooda naan nijama solluren' },
    { id: 7, dimension: 'trust', direction: 'them', text: 'En friend sollura nerathukku varuvanga' },
    { id: 8, dimension: 'trust', direction: 'me', text: 'En friend-kku thevayana nerathula naan iruppean' },
    { id: 9, dimension: 'trust', direction: 'them', text: 'Mukkiya vishayam-a en friend-kitta sollamudiyum' },
    { id: 10, dimension: 'trust', direction: 'me', text: 'En friend-oda ragasiyam-a naan paathukuven' },
    { id: 11, dimension: 'trust', direction: 'them', text: 'Thappu aana en friend othukuvaanga' },
    { id: 12, dimension: 'trust', direction: 'me', text: 'En thappu-kku naan poruppeduppean' },
    { id: 13, dimension: 'trust', direction: 'them', text: 'En friend enna pathi vera yaarukittayum thappa pesala' },
    { id: 14, dimension: 'trust', direction: 'me', text: 'Naan en friend-a pathi nalla-va dhan pesuren' },
    { id: 15, dimension: 'trust', direction: 'them', text: 'Indha friendship-la naan safe-a feel pannuren' },

    // Communication (15 questions)
    { id: 16, dimension: 'communication', direction: 'them', text: 'Naan pesumpodhu en friend nalla kekkuvanga' },
    { id: 17, dimension: 'communication', direction: 'me', text: 'Naan en friend kitta pesumpodhu kavanam kudukkuren' },
    { id: 18, dimension: 'communication', direction: 'them', text: 'En friend aarvamudhan kelvi kekkuvanga' },
    { id: 19, dimension: 'communication', direction: 'me', text: 'Naan en friend-oda vazhkai pathi kelvi kekkuren' },
    { id: 20, dimension: 'communication', direction: 'them', text: 'En friend thelivaaga pesuvanga' },
    { id: 21, dimension: 'communication', direction: 'me', text: 'Naan en ninaipu-a thelivaaga solluven' },
    { id: 22, dimension: 'communication', direction: 'them', text: 'En friend message-kku seekiram reply pannuvanga' },
    { id: 23, dimension: 'communication', direction: 'me', text: 'Naan en friend-oda message-kku seekiram reply pannuven' },
    { id: 24, dimension: 'communication', direction: 'them', text: 'En friend avanga vazhkaila nadakkara mukkiya vishayam solluvanga' },
    { id: 25, dimension: 'communication', direction: 'me', text: 'Naan mukkiya vishayam nadandha en friend-kku solluren' },
    { id: 26, dimension: 'communication', direction: 'them', text: 'Kashtamaana vishayam-a kooda en friend pesuvanga' },
    { id: 27, dimension: 'communication', direction: 'me', text: 'Naan kashtamaana vishayam-a en friend-kitta pesalaam' },
    { id: 28, dimension: 'communication', direction: 'them', text: 'Enga pesarathu-a en friend nenjula vechukuvaanga' },
    { id: 29, dimension: 'communication', direction: 'me', text: 'Naan en friend sollara mukkiya vishayam nyabagam vechukuven' },
    { id: 30, dimension: 'communication', direction: 'them', text: 'En friend kooda pesa romba easy' },

    // Emotional Support (15 questions)
    { id: 31, dimension: 'support', direction: 'them', text: 'Kashtamaana nerathula en friend ennoda irupanga' },
    { id: 32, dimension: 'support', direction: 'me', text: 'En friend kashta-padumbodhu naan udhavi pannuren' },
    { id: 33, dimension: 'support', direction: 'them', text: 'En friend en elagaam-a purinchukuvaanga' },
    { id: 34, dimension: 'support', direction: 'me', text: 'Naan en friend-oda elagaam-a purinchukuven' },
    { id: 35, dimension: 'support', direction: 'them', text: 'Naan success aana en friend sandhoshapa-duvaanga' },
    { id: 36, dimension: 'support', direction: 'me', text: 'Naan en friend-oda success-a nenjodu sandhoshapa-duven' },
    { id: 37, dimension: 'support', direction: 'them', text: 'Naan kavalai-padumpodhu en friend thaetruvanga' },
    { id: 38, dimension: 'support', direction: 'me', text: 'Naan en friend-kku manathin udhavi kudukkuren' },
    { id: 39, dimension: 'support', direction: 'them', text: 'Prachanaila en friend dhairiyam kudukkuvanga' },
    { id: 40, dimension: 'support', direction: 'me', text: 'Naan en friend-a uyarthuvean uthsaham kuduppen' },
    { id: 41, dimension: 'support', direction: 'them', text: 'En friend en kashtatha purinjukuvaanga' },
    { id: 42, dimension: 'support', direction: 'me', text: 'Naan en friend-oda kashtatha purinchukuven' },
    { id: 43, dimension: 'support', direction: 'them', text: 'En friend eppo-vaadhu visaarikka varuvaanga' },
    { id: 44, dimension: 'support', direction: 'me', text: 'Naan en friend epdi irukkanga-nu keppean' },
    { id: 45, dimension: 'support', direction: 'them', text: 'En friend kooda manathin-a safe-a feel pannuren' },

    // Mutual Respect (15 questions)
    { id: 46, dimension: 'respect', direction: 'them', text: 'Enaku oru karu irundhalum en friend mariyathai kudukkuvanga' },
    { id: 47, dimension: 'respect', direction: 'me', text: 'Veru-paatta irundhalum naan en friend-oda ninaipu-a mariyathai pannuven' },
    { id: 48, dimension: 'respect', direction: 'them', text: 'En friend en neram-a matipiduvanga' },
    { id: 49, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda neram-a ninachikuren' },
    { id: 50, dimension: 'respect', direction: 'them', text: 'En friend enna ollavanu yen-drikkaruvaanga' },
    { id: 51, dimension: 'respect', direction: 'me', text: 'Naan en friend-a ollavanu yen-drikkaruven' },
    { id: 52, dimension: 'respect', direction: 'them', text: 'En friend en vazhkaila edukkara mudivu-kku mariyathai kudukkuvanga' },
    { id: 53, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda mudivu-a uthavi pannuven' },
    { id: 54, dimension: 'respect', direction: 'them', text: 'En friend enna kalaika maatanga' },
    { id: 55, dimension: 'respect', direction: 'me', text: 'Naan en friend-a vali kudukkum kalai panna matten' },
    { id: 56, dimension: 'respect', direction: 'them', text: 'En friend enna samam-a treat pannuvanga' },
    { id: 57, dimension: 'respect', direction: 'me', text: 'Naan en friend-a samam-a treat pannuven' },
    { id: 58, dimension: 'respect', direction: 'them', text: 'En friend en thanimal-a mariyathai pannuvanga' },
    { id: 59, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda thanimal-a mariyathai pannuven' },
    { id: 60, dimension: 'respect', direction: 'them', text: 'Naan matipudan nadakuren-nu feel pannuren' },

    // Boundaries (15 questions)
    { id: 61, dimension: 'boundaries', direction: 'them', text: 'En friend en ellai-a mariyathai pannuvanga' },
    { id: 62, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-oda ellai-a kaapaathikuren' },
    { id: 63, dimension: 'boundaries', direction: 'them', text: 'En friend enna vendam-nu sonnaa force panna maataanga' },
    { id: 64, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-a ishtamillaama pannikka sonnaa kekka matten' },
    { id: 65, dimension: 'boundaries', direction: 'them', text: 'Enakku idam venum-na en friend purinchukuvaanga' },
    { id: 66, dimension: 'boundaries', direction: 'me', text: 'En friend-kku idam venum-na kuduppen' },
    { id: 67, dimension: 'boundaries', direction: 'them', text: 'Naan "mudiyathu"-nu sollumbodhu en friend yen-drikaruvaanga' },
    { id: 68, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-oda "mudiyathu"-nu nandraga yen-drikaruven' },
    { id: 69, dimension: 'boundaries', direction: 'them', text: 'En friend romba kekka maataanga' },
    { id: 70, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-a romba vecchu azhuthathu matten' },
    { id: 71, dimension: 'boundaries', direction: 'them', text: 'En friend en vera nanban-a mariyathai pannuvanga' },
    { id: 72, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-kku vera nanban irukrathu-a uthavi pannuven' },
    { id: 73, dimension: 'boundaries', direction: 'them', text: 'En friend avanga ellai-a thelivaaga solluvanga' },
    { id: 74, dimension: 'boundaries', direction: 'me', text: 'Naan en ellai-a en friend-kitta thelivaaga solluven' },
    { id: 75, dimension: 'boundaries', direction: 'them', text: 'Friendship nerodu irukum oruthar maththum illa' },

    // Personal Growth (15 questions)
    { id: 76, dimension: 'growth', direction: 'them', text: 'En friend enna munneradha uthavi pannuvanga' },
    { id: 77, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda valar aasai-a uthavi pannuven' },
    { id: 78, dimension: 'growth', direction: 'them', text: 'En friend enna nalla pannumadi azhaippanga (nallathukku)' },
    { id: 79, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda theemai-a adaya udhavi pannuven' },
    { id: 80, dimension: 'growth', direction: 'them', text: 'Naan vetriya adaiyum-bodhu en friend bayapa-dala' },
    { id: 81, dimension: 'growth', direction: 'me', text: 'En friend vetriya adaiyum-bodhu naan nejamavey sandhoshapa-duven' },
    { id: 82, dimension: 'growth', direction: 'them', text: 'En friend enna en kangaani thodi uthsaham kudukkuvanga' },
    { id: 83, dimension: 'growth', direction: 'me', text: 'Naan en friend-a kanavu thoda uthsaham kuduppen' },
    { id: 84, dimension: 'growth', direction: 'them', text: 'Naan kekkum-bodhu en friend nalla urai kudukkuvanga' },
    { id: 85, dimension: 'growth', direction: 'me', text: 'En friend kekkum-bodhu naan udhavi-karam urai kudukkuren' },
    { id: 86, dimension: 'growth', direction: 'them', text: 'En friend en thappu-lerndhu kattru-kolla uthavi pannuvanga' },
    { id: 87, dimension: 'growth', direction: 'me', text: 'Naan en friend-a kashtam-lerndhu kattru valaraa uthavi pannuven' },
    { id: 88, dimension: 'growth', direction: 'them', text: 'Indha nanban-naal naan oru manidan-a valarndhirken' },
    { id: 89, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda valarchi-kku nalla uthavi pannuren' },
    { id: 90, dimension: 'growth', direction: 'them', text: 'En friend pudhusa try panna uthavi pannuvanga' },

    // Fun & Enjoyment (15 questions)
    { id: 91, dimension: 'fun', direction: 'them', text: 'En friend kooda neram pogarathu romba santhosham' },
    { id: 92, dimension: 'fun', direction: 'me', text: 'En friend en kooda irukka pudikum-nu theriyum' },
    { id: 93, dimension: 'fun', direction: 'them', text: 'En friend enna sirikaavechuraanga' },
    { id: 94, dimension: 'fun', direction: 'me', text: 'Naan en friend-kku santhoshamum sirippu-m kudukkuren' },
    { id: 95, dimension: 'fun', direction: 'them', text: 'En friend kooda irundhaa neram seekiram poidum' },
    { id: 96, dimension: 'fun', direction: 'me', text: 'Naanum en friend-um nalla ninaivugal undaakkurom' },
    { id: 97, dimension: 'fun', direction: 'them', text: 'En friend munn-erutha seydhiduvanga' },
    { id: 98, dimension: 'fun', direction: 'me', text: 'Naan nallan neram pogarthukku muyarchi pannuren' },
    { id: 99, dimension: 'fun', direction: 'them', text: 'En friend en sirippu-a pidikkum' },
    { id: 100, dimension: 'fun', direction: 'me', text: 'Naan en friend-oda tharamaana izhappan-a rasikkiren' },
    { id: 101, dimension: 'fun', direction: 'them', text: 'En friend enna pudhusa vishayathukku azhai-ppanga' },
    { id: 102, dimension: 'fun', direction: 'me', text: 'Naan interest-aana vishayatha share pannuren' },
    { id: 103, dimension: 'fun', direction: 'them', text: 'En friend kooda irundhaa en tension korayum' },
    { id: 104, dimension: 'fun', direction: 'me', text: 'En friend ennoda amaithiyaaga iruppanga' },
    { id: 105, dimension: 'fun', direction: 'them', text: 'Naan en friend-a paakka romba wait pannuren' },

    // Conflict Resolution (15 questions)
    { id: 106, dimension: 'conflict', direction: 'them', text: 'En friend prachana-a thappithukkama neradiyaaga pesuvanga' },
    { id: 107, dimension: 'conflict', direction: 'me', text: 'Naan prachana-a vidaamal thelivaaga pesuren' },
    { id: 108, dimension: 'conflict', direction: 'them', text: 'Enaku poru irundhalum en friend amaithiyaaga irupanga' },
    { id: 109, dimension: 'conflict', direction: 'me', text: 'Sandai-la kooda naan mariyathaiyudan iruken' },
    { id: 110, dimension: 'conflict', direction: 'them', text: 'Thappu pannaa en friend manathodaan mannipu keppanga' },
    { id: 111, dimension: 'conflict', direction: 'me', text: 'Naan thappu panninaa nejamavey mannipu keppen' },
    { id: 112, dimension: 'conflict', direction: 'them', text: 'En friend nenjodu iranguvanga' },
    { id: 113, dimension: 'conflict', direction: 'me', text: 'Poru-la naduve vazhi theduvean' },
    { id: 114, dimension: 'conflict', direction: 'them', text: 'Sandai mudinchaa en friend mannichitu mundhi poiduvanga' },
    { id: 115, dimension: 'conflict', direction: 'me', text: 'Naan kovam vechukka matten en friend-a mannikkuren' },
    { id: 116, dimension: 'conflict', direction: 'them', text: 'En friend pazhaya thappu-a thirupi thirupi sollala' },
    { id: 117, dimension: 'conflict', direction: 'me', text: 'Naan pazhaya vishayam pidichi vechukka matten' },
    { id: 118, dimension: 'conflict', direction: 'them', text: 'Sandai-la en friend en paarvaiya purinchukka try pannuvanga' },
    { id: 119, dimension: 'conflict', direction: 'me', text: 'Naan en friend-oda paarvaiya paakka muyarchi pannuven' },
    { id: 120, dimension: 'conflict', direction: 'them', text: 'Sandai-a nallavitham theerkurom' },

    // Loyalty (15 questions)
    { id: 121, dimension: 'loyalty', direction: 'them', text: 'Yaaraachu tappa sonnaa en friend enakku niththuruvanga' },
    { id: 122, dimension: 'loyalty', direction: 'me', text: 'En friend illaamba naan kaapaathippen' },
    { id: 123, dimension: 'loyalty', direction: 'them', text: 'En friend enga nanban-a muthal idam kudukkuvanga' },
    { id: 124, dimension: 'loyalty', direction: 'me', text: 'Naan enga nanban-a en vazhkaila muthal idam vaikuren' },
    { id: 125, dimension: 'loyalty', direction: 'them', text: 'En friend endrum ore mathiri irupanga' },
    { id: 126, dimension: 'loyalty', direction: 'me', text: 'Naan nambikaiyaana ore mathiri iruken' },
    { id: 127, dimension: 'loyalty', direction: 'them', text: 'Kashtamaana nerathila en friend vittutu poga maatanga' },
    { id: 128, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-oda kashtathila uthavi pannuren' },
    { id: 129, dimension: 'loyalty', direction: 'them', text: 'En friend enna avanga vazhkaila serppanga' },
    { id: 130, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-a en vazhkaila serppa muyarchi pannuren' },
    { id: 131, dimension: 'loyalty', direction: 'them', text: 'En friend kadeisi nerathila thirumanatha cancel panna maatanga (avesaram illama)' },
    { id: 132, dimension: 'loyalty', direction: 'me', text: 'Naan en vaakku-a kaapaathikuren' },
    { id: 133, dimension: 'loyalty', direction: 'them', text: 'En friend en kaapu paathuppanga' },
    { id: 134, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-a yaappozhudhum uthavi pannuren' },
    { id: 135, dimension: 'loyalty', direction: 'them', text: 'En friend-a neraya naal nambalam' },

    // Authenticity (15 questions)
    { id: 136, dimension: 'authenticity', direction: 'them', text: 'En friend nejamavey irupanga poi sollamaatanga' },
    { id: 137, dimension: 'authenticity', direction: 'me', text: 'En friend kooda naan nejamavey irukkamudiyum' },
    { id: 138, dimension: 'authenticity', direction: 'them', text: 'En friend unmaiyaana ninaipu-a solluvaanga' },
    { id: 139, dimension: 'authenticity', direction: 'me', text: 'Indha nanban-naal naan nejamavey irukkuren' },
    { id: 140, dimension: 'authenticity', direction: 'them', text: 'En friend yaarodayum nadikka maataanga' },
    { id: 141, dimension: 'authenticity', direction: 'me', text: 'En friend kooda mugham maatham pottu irukkanum-nu thonaala' },
    { id: 142, dimension: 'authenticity', direction: 'them', text: 'En friend avanga palaveenaa-a othukuvaanga' },
    { id: 143, dimension: 'authenticity', direction: 'me', text: 'En palaveenaa pakka-a kaatturathu safe-a feel pannuren' },
    { id: 144, dimension: 'authenticity', direction: 'them', text: 'En friend sollurathum panradhum onnu' },
    { id: 145, dimension: 'authenticity', direction: 'me', text: 'Naan solluratha naan pannuren' },
    { id: 146, dimension: 'authenticity', direction: 'them', text: 'En friend kalla vilaiyaatu aadala' },
    { id: 147, dimension: 'authenticity', direction: 'me', text: 'Naan neradiyaaga nejamavey iruken' },
    { id: 148, dimension: 'authenticity', direction: 'them', text: 'En friend-oda ezhangaal nejamanu namburen' },
    { id: 149, dimension: 'authenticity', direction: 'me', text: 'En friend-kku naan nalla ninachukuren-nu namburaanga' },
    { id: 150, dimension: 'authenticity', direction: 'them', text: 'Indha nanban nejamaanavanga arthamerikka' },
  ]
};

export const SCORE_CATEGORIES = [
  { min: 85, max: 100, label: 'Thriving Friendship', color: '#10b981', emoji: '🌟' },
  { min: 70, max: 84, label: 'Healthy Friendship', color: '#3b82f6', emoji: '💙' },
  { min: 55, max: 69, label: 'Moderate Friendship', color: '#eab308', emoji: '⚡' },
  { min: 40, max: 54, label: 'Struggling Friendship', color: '#f97316', emoji: '⚠️' },
  { min: 0, max: 39, label: 'Unhealthy Friendship', color: '#ef4444', emoji: '🚨' }
];

export const getScoreCategory = (score) => {
  return SCORE_CATEGORIES.find(cat => score >= cat.min && score <= cat.max) || SCORE_CATEGORIES[4];
};
