// 150 Questions across 10 dimensions for Friendship Health Assessment
export const DIMENSIONS = [
  { id: 'trust', name: 'Trust & Reliability', icon: '🤝' },
  { id: 'communication', name: 'Communication', icon: '💬' },
  { id: 'support', name: 'Emotional Support', icon: '❤️' },
  { id: 'respect', name: 'Mutual Respect', icon: '🙏' },
  { id: 'boundaries', name: 'Boundaries', icon: '🛡️' },
  { id: 'growth', name: 'Personal Growth', icon: '🌱' },
  { id: 'fun', name: 'Fun & Enjoyment', icon: '🎉' },
  { id: 'conflict', name: 'Conflict Resolution', icon: '⚖️' },
  { id: 'loyalty', name: 'Loyalty', icon: '🔒' },
  { id: 'authenticity', name: 'Authenticity', icon: '✨' }
];

export const QUESTIONS = {
  english: [
    // Trust & Reliability (15 questions)
    { id: 1, dimension: 'trust', direction: 'them', text: 'My friend keeps their promises to me' },
    { id: 2, dimension: 'trust', direction: 'me', text: 'I consistently follow through on commitments I make to my friend' },
    { id: 3, dimension: 'trust', direction: 'them', text: 'I can confide in my friend without fear of judgment' },
    { id: 4, dimension: 'trust', direction: 'me', text: 'I keep my friend\'s secrets safe' },
    { id: 5, dimension: 'trust', direction: 'them', text: 'My friend is honest with me, even when it\'s difficult' },
    { id: 6, dimension: 'trust', direction: 'me', text: 'I am truthful with my friend, even about uncomfortable topics' },
    { id: 7, dimension: 'trust', direction: 'them', text: 'My friend shows up when they say they will' },
    { id: 8, dimension: 'trust', direction: 'me', text: 'I am reliable when my friend needs me' },
    { id: 9, dimension: 'trust', direction: 'them', text: 'I trust my friend with important information about my life' },
    { id: 10, dimension: 'trust', direction: 'me', text: 'I handle my friend\'s personal information responsibly' },
    { id: 11, dimension: 'trust', direction: 'them', text: 'My friend admits when they make mistakes' },
    { id: 12, dimension: 'trust', direction: 'me', text: 'I take accountability for my errors in our friendship' },
    { id: 13, dimension: 'trust', direction: 'them', text: 'My friend doesn\'t gossip about me to others' },
    { id: 14, dimension: 'trust', direction: 'me', text: 'I speak positively about my friend when they\'re not around' },
    { id: 15, dimension: 'trust', direction: 'them', text: 'I feel secure in this friendship' },

    // Communication (15 questions)
    { id: 16, dimension: 'communication', direction: 'them', text: 'My friend listens actively when I speak' },
    { id: 17, dimension: 'communication', direction: 'me', text: 'I give my friend my full attention during conversations' },
    { id: 18, dimension: 'communication', direction: 'them', text: 'My friend asks follow-up questions showing genuine interest' },
    { id: 19, dimension: 'communication', direction: 'me', text: 'I ask thoughtful questions about my friend\'s life' },
    { id: 20, dimension: 'communication', direction: 'them', text: 'My friend communicates clearly and directly' },
    { id: 21, dimension: 'communication', direction: 'me', text: 'I express my thoughts and feelings clearly to my friend' },
    { id: 22, dimension: 'communication', direction: 'them', text: 'My friend responds to my messages in a reasonable time' },
    { id: 23, dimension: 'communication', direction: 'me', text: 'I reply to my friend\'s messages promptly' },
    { id: 24, dimension: 'communication', direction: 'them', text: 'My friend shares important updates from their life' },
    { id: 25, dimension: 'communication', direction: 'me', text: 'I keep my friend informed about significant events in my life' },
    { id: 26, dimension: 'communication', direction: 'them', text: 'My friend is comfortable discussing difficult topics' },
    { id: 27, dimension: 'communication', direction: 'me', text: 'I can talk to my friend about challenging subjects' },
    { id: 28, dimension: 'communication', direction: 'them', text: 'My friend remembers details from our conversations' },
    { id: 29, dimension: 'communication', direction: 'me', text: 'I remember important things my friend tells me' },
    { id: 30, dimension: 'communication', direction: 'them', text: 'Communication feels natural and easy with my friend' },

    // Emotional Support (15 questions)
    { id: 31, dimension: 'support', direction: 'them', text: 'My friend is there for me during difficult times' },
    { id: 32, dimension: 'support', direction: 'me', text: 'I provide support when my friend is struggling' },
    { id: 33, dimension: 'support', direction: 'them', text: 'My friend validates my feelings' },
    { id: 34, dimension: 'support', direction: 'me', text: 'I acknowledge and validate my friend\'s emotions' },
    { id: 35, dimension: 'support', direction: 'them', text: 'My friend celebrates my successes and achievements' },
    { id: 36, dimension: 'support', direction: 'me', text: 'I genuinely celebrate my friend\'s accomplishments' },
    { id: 37, dimension: 'support', direction: 'them', text: 'My friend offers comfort when I\'m upset' },
    { id: 38, dimension: 'support', direction: 'me', text: 'I provide emotional comfort to my friend when needed' },
    { id: 39, dimension: 'support', direction: 'them', text: 'My friend encourages me during challenges' },
    { id: 40, dimension: 'support', direction: 'me', text: 'I motivate and encourage my friend' },
    { id: 41, dimension: 'support', direction: 'them', text: 'My friend shows empathy for my struggles' },
    { id: 42, dimension: 'support', direction: 'me', text: 'I empathize with my friend\'s difficulties' },
    { id: 43, dimension: 'support', direction: 'them', text: 'My friend checks in on me regularly' },
    { id: 44, dimension: 'support', direction: 'me', text: 'I reach out to see how my friend is doing' },
    { id: 45, dimension: 'support', direction: 'them', text: 'I feel emotionally safe with my friend' },

    // Mutual Respect (15 questions)
    { id: 46, dimension: 'respect', direction: 'them', text: 'My friend respects my opinions, even when we disagree' },
    { id: 47, dimension: 'respect', direction: 'me', text: 'I respect my friend\'s viewpoints, even if different from mine' },
    { id: 48, dimension: 'respect', direction: 'them', text: 'My friend values my time' },
    { id: 49, dimension: 'respect', direction: 'me', text: 'I am considerate of my friend\'s schedule and commitments' },
    { id: 50, dimension: 'respect', direction: 'them', text: 'My friend accepts me as I am' },
    { id: 51, dimension: 'respect', direction: 'me', text: 'I accept my friend without trying to change them' },
    { id: 52, dimension: 'respect', direction: 'them', text: 'My friend respects my life choices' },
    { id: 53, dimension: 'respect', direction: 'me', text: 'I support my friend\'s decisions and life path' },
    { id: 54, dimension: 'respect', direction: 'them', text: 'My friend doesn\'t belittle or mock me' },
    { id: 55, dimension: 'respect', direction: 'me', text: 'I avoid making fun of my friend in hurtful ways' },
    { id: 56, dimension: 'respect', direction: 'them', text: 'My friend treats me as an equal' },
    { id: 57, dimension: 'respect', direction: 'me', text: 'I treat my friend as an equal partner in the friendship' },
    { id: 58, dimension: 'respect', direction: 'them', text: 'My friend respects my privacy' },
    { id: 59, dimension: 'respect', direction: 'me', text: 'I respect my friend\'s need for privacy' },
    { id: 60, dimension: 'respect', direction: 'them', text: 'I feel valued and appreciated by my friend' },

    // Boundaries (15 questions)
    { id: 61, dimension: 'boundaries', direction: 'them', text: 'My friend respects my boundaries' },
    { id: 62, dimension: 'boundaries', direction: 'me', text: 'I honor my friend\'s boundaries' },
    { id: 63, dimension: 'boundaries', direction: 'them', text: 'My friend doesn\'t pressure me to do things I\'m uncomfortable with' },
    { id: 64, dimension: 'boundaries', direction: 'me', text: 'I don\'t push my friend beyond their comfort zone' },
    { id: 65, dimension: 'boundaries', direction: 'them', text: 'My friend understands when I need space' },
    { id: 66, dimension: 'boundaries', direction: 'me', text: 'I give my friend space when they need it' },
    { id: 67, dimension: 'boundaries', direction: 'them', text: 'My friend accepts my "no" without guilt-tripping' },
    { id: 68, dimension: 'boundaries', direction: 'me', text: 'I accept my friend\'s "no" gracefully' },
    { id: 69, dimension: 'boundaries', direction: 'them', text: 'My friend doesn\'t make excessive demands on my time' },
    { id: 70, dimension: 'boundaries', direction: 'me', text: 'I am mindful of not overwhelming my friend with demands' },
    { id: 71, dimension: 'boundaries', direction: 'them', text: 'My friend respects my other relationships' },
    { id: 72, dimension: 'boundaries', direction: 'me', text: 'I support my friend having other friendships' },
    { id: 73, dimension: 'boundaries', direction: 'them', text: 'My friend communicates their boundaries clearly' },
    { id: 74, dimension: 'boundaries', direction: 'me', text: 'I express my boundaries clearly to my friend' },
    { id: 75, dimension: 'boundaries', direction: 'them', text: 'The friendship feels balanced, not one-sided' },

    // Personal Growth (15 questions)
    { id: 76, dimension: 'growth', direction: 'them', text: 'My friend encourages my personal development' },
    { id: 77, dimension: 'growth', direction: 'me', text: 'I support my friend\'s growth and aspirations' },
    { id: 78, dimension: 'growth', direction: 'them', text: 'My friend challenges me to be better (in a positive way)' },
    { id: 79, dimension: 'growth', direction: 'me', text: 'I help my friend reach their potential' },
    { id: 80, dimension: 'growth', direction: 'them', text: 'My friend isn\'t threatened by my success' },
    { id: 81, dimension: 'growth', direction: 'me', text: 'I feel genuinely happy about my friend\'s achievements' },
    { id: 82, dimension: 'growth', direction: 'them', text: 'My friend inspires me to pursue my goals' },
    { id: 83, dimension: 'growth', direction: 'me', text: 'I encourage my friend to chase their dreams' },
    { id: 84, dimension: 'growth', direction: 'them', text: 'My friend gives constructive feedback when I ask for it' },
    { id: 85, dimension: 'growth', direction: 'me', text: 'I offer helpful advice when my friend seeks it' },
    { id: 86, dimension: 'growth', direction: 'them', text: 'My friend helps me learn from my mistakes' },
    { id: 87, dimension: 'growth', direction: 'me', text: 'I help my friend learn and grow from challenges' },
    { id: 88, dimension: 'growth', direction: 'them', text: 'I\'ve grown as a person because of this friendship' },
    { id: 89, dimension: 'growth', direction: 'me', text: 'I contribute positively to my friend\'s personal development' },
    { id: 90, dimension: 'growth', direction: 'them', text: 'My friend supports me trying new things' },

    // Fun & Enjoyment (15 questions)
    { id: 91, dimension: 'fun', direction: 'them', text: 'I genuinely enjoy spending time with my friend' },
    { id: 92, dimension: 'fun', direction: 'me', text: 'My friend seems to enjoy my company' },
    { id: 93, dimension: 'fun', direction: 'them', text: 'My friend makes me laugh' },
    { id: 94, dimension: 'fun', direction: 'me', text: 'I bring joy and laughter to my friend' },
    { id: 95, dimension: 'fun', direction: 'them', text: 'Time passes quickly when I\'m with my friend' },
    { id: 96, dimension: 'fun', direction: 'me', text: 'My friend and I create fun memories together' },
    { id: 97, dimension: 'fun', direction: 'them', text: 'My friend initiates plans to hang out' },
    { id: 98, dimension: 'fun', direction: 'me', text: 'I make an effort to spend quality time with my friend' },
    { id: 99, dimension: 'fun', direction: 'them', text: 'My friend shares my sense of humor' },
    { id: 100, dimension: 'fun', direction: 'me', text: 'I appreciate my friend\'s personality and quirks' },
    { id: 101, dimension: 'fun', direction: 'them', text: 'My friend introduces me to new experiences' },
    { id: 102, dimension: 'fun', direction: 'me', text: 'I share interesting activities with my friend' },
    { id: 103, dimension: 'fun', direction: 'them', text: 'Being with my friend reduces my stress' },
    { id: 104, dimension: 'fun', direction: 'me', text: 'My friend feels comfortable and relaxed around me' },
    { id: 105, dimension: 'fun', direction: 'them', text: 'I look forward to seeing my friend' },

    // Conflict Resolution (15 questions)
    { id: 106, dimension: 'conflict', direction: 'them', text: 'My friend addresses issues directly rather than avoiding them' },
    { id: 107, dimension: 'conflict', direction: 'me', text: 'I communicate problems rather than letting them fester' },
    { id: 108, dimension: 'conflict', direction: 'them', text: 'My friend stays calm during disagreements' },
    { id: 109, dimension: 'conflict', direction: 'me', text: 'I remain respectful even when we\'re in conflict' },
    { id: 110, dimension: 'conflict', direction: 'them', text: 'My friend apologizes sincerely when they\'re wrong' },
    { id: 111, dimension: 'conflict', direction: 'me', text: 'I offer genuine apologies when I make mistakes' },
    { id: 112, dimension: 'conflict', direction: 'them', text: 'My friend is willing to compromise' },
    { id: 113, dimension: 'conflict', direction: 'me', text: 'I look for middle ground during disagreements' },
    { id: 114, dimension: 'conflict', direction: 'them', text: 'My friend forgives and moves forward after conflicts' },
    { id: 115, dimension: 'conflict', direction: 'me', text: 'I let go of grudges and forgive my friend' },
    { id: 116, dimension: 'conflict', direction: 'them', text: 'My friend doesn\'t bring up past mistakes repeatedly' },
    { id: 117, dimension: 'conflict', direction: 'me', text: 'I don\'t hold past issues over my friend\'s head' },
    { id: 118, dimension: 'conflict', direction: 'them', text: 'My friend tries to understand my perspective during conflicts' },
    { id: 119, dimension: 'conflict', direction: 'me', text: 'I make an effort to see things from my friend\'s viewpoint' },
    { id: 120, dimension: 'conflict', direction: 'them', text: 'We resolve conflicts constructively' },

    // Loyalty (15 questions)
    { id: 121, dimension: 'loyalty', direction: 'them', text: 'My friend stands up for me when others criticize me' },
    { id: 122, dimension: 'loyalty', direction: 'me', text: 'I defend my friend when they\'re not present' },
    { id: 123, dimension: 'loyalty', direction: 'them', text: 'My friend prioritizes our friendship' },
    { id: 124, dimension: 'loyalty', direction: 'me', text: 'I make our friendship a priority in my life' },
    { id: 125, dimension: 'loyalty', direction: 'them', text: 'My friend is consistent in our friendship' },
    { id: 126, dimension: 'loyalty', direction: 'me', text: 'I am dependable and consistent as a friend' },
    { id: 127, dimension: 'loyalty', direction: 'them', text: 'My friend doesn\'t abandon me during tough times' },
    { id: 128, dimension: 'loyalty', direction: 'me', text: 'I stick by my friend through their challenges' },
    { id: 129, dimension: 'loyalty', direction: 'them', text: 'My friend includes me in their life' },
    { id: 130, dimension: 'loyalty', direction: 'me', text: 'I make an effort to include my friend in my life' },
    { id: 131, dimension: 'loyalty', direction: 'them', text: 'My friend doesn\'t cancel plans at the last minute (except for emergencies)' },
    { id: 132, dimension: 'loyalty', direction: 'me', text: 'I honor my commitments to my friend' },
    { id: 133, dimension: 'loyalty', direction: 'them', text: 'My friend has my back' },
    { id: 134, dimension: 'loyalty', direction: 'me', text: 'I support my friend unconditionally' },
    { id: 135, dimension: 'loyalty', direction: 'them', text: 'I can count on my friend long-term' },

    // Authenticity (15 questions)
    { id: 136, dimension: 'authenticity', direction: 'them', text: 'My friend is genuine and authentic with me' },
    { id: 137, dimension: 'authenticity', direction: 'me', text: 'I can be my true self around my friend' },
    { id: 138, dimension: 'authenticity', direction: 'them', text: 'My friend shares their real thoughts and feelings' },
    { id: 139, dimension: 'authenticity', direction: 'me', text: 'I express my authentic self in this friendship' },
    { id: 140, dimension: 'authenticity', direction: 'them', text: 'My friend doesn\'t pretend to be someone they\'re not' },
    { id: 141, dimension: 'authenticity', direction: 'me', text: 'I don\'t feel the need to wear a mask around my friend' },
    { id: 142, dimension: 'authenticity', direction: 'them', text: 'My friend admits their vulnerabilities' },
    { id: 143, dimension: 'authenticity', direction: 'me', text: 'I feel safe showing my vulnerable side to my friend' },
    { id: 144, dimension: 'authenticity', direction: 'them', text: 'My friend\'s words match their actions' },
    { id: 145, dimension: 'authenticity', direction: 'me', text: 'I practice what I preach in this friendship' },
    { id: 146, dimension: 'authenticity', direction: 'them', text: 'My friend doesn\'t play games or manipulate' },
    { id: 147, dimension: 'authenticity', direction: 'me', text: 'I am straightforward and honest in this friendship' },
    { id: 148, dimension: 'authenticity', direction: 'them', text: 'I trust my friend\'s intentions are genuine' },
    { id: 149, dimension: 'authenticity', direction: 'me', text: 'My friend trusts that I have their best interests at heart' },
    { id: 150, dimension: 'authenticity', direction: 'them', text: 'This friendship feels real and meaningful' },
  ],
  tanglish: [
    // Trust & Reliability (15 questions)
    { id: 1, dimension: 'trust', direction: 'them', text: 'En friend avanga promise-a keep pannuvanga' },
    { id: 2, dimension: 'trust', direction: 'me', text: 'Naan en friend-kku commitment kuduthurundha follow through pannuven' },
    { id: 3, dimension: 'trust', direction: 'them', text: 'En friend-kitta judge pannama confide panna mudiyum' },
    { id: 4, dimension: 'trust', direction: 'me', text: 'Naan en friend-oda secrets-a safe-a vechukuven' },
    { id: 5, dimension: 'trust', direction: 'them', text: 'En friend kashtamaana vishayathula kooda honest-a irupanga' },
    { id: 6, dimension: 'trust', direction: 'me', text: 'Naan uncomfortable topics-la kooda unmaiya solluven' },
    { id: 7, dimension: 'trust', direction: 'them', text: 'En friend sollura time-kku vara panga' },
    { id: 8, dimension: 'trust', direction: 'me', text: 'En friend-kku naan reliable-a iruken' },
    { id: 9, dimension: 'trust', direction: 'them', text: 'Important information-a en friend-kitta share panna trust panren' },
    { id: 10, dimension: 'trust', direction: 'me', text: 'En friend-oda personal info-va responsible-a handle pannuven' },
    { id: 11, dimension: 'trust', direction: 'them', text: 'En friend thappu pannurappa admit pannuvanga' },
    { id: 12, dimension: 'trust', direction: 'me', text: 'Naan en mistakes-kku accountability edukkuven' },
    { id: 13, dimension: 'trust', direction: 'them', text: 'En friend enna pathi vera aalukitta gossip pannala' },
    { id: 14, dimension: 'trust', direction: 'me', text: 'Naan en friend-a pathi positive-a dhan pesuren' },
    { id: 15, dimension: 'trust', direction: 'them', text: 'Indha friendship-la naan secure-a feel pannuren' },

    // Communication (15 questions)
    { id: 16, dimension: 'communication', direction: 'them', text: 'En friend naan pesumbodhellam active-a kekkuvanga' },
    { id: 17, dimension: 'communication', direction: 'me', text: 'Naan en friend kitta pesumpodhu full attention kudukkuren' },
    { id: 18, dimension: 'communication', direction: 'them', text: 'En friend genuine interest-oda follow-up questions kekkuvanga' },
    { id: 19, dimension: 'communication', direction: 'me', text: 'Naan en friend-oda life pathi thoughtful questions kekkuren' },
    { id: 20, dimension: 'communication', direction: 'them', text: 'En friend clear-a direct-a communicate pannuvanga' },
    { id: 21, dimension: 'communication', direction: 'me', text: 'Naan en thoughts-a feelings-a clear-a express pannuven' },
    { id: 22, dimension: 'communication', direction: 'them', text: 'En friend messages-kku reasonable time-la reply pannuvanga' },
    { id: 23, dimension: 'communication', direction: 'me', text: 'Naan en friend-oda messages-kku prompt-a reply pannuven' },
    { id: 24, dimension: 'communication', direction: 'them', text: 'En friend avanga life-la important updates share pannuvanga' },
    { id: 25, dimension: 'communication', direction: 'me', text: 'Naan significant events pathi en friend-kku inform pannuven' },
    { id: 26, dimension: 'communication', direction: 'them', text: 'En friend difficult topics discuss panna comfortable-a irupanga' },
    { id: 27, dimension: 'communication', direction: 'me', text: 'Naan challenging subjects pathi en friend-kitta pesalaam' },
    { id: 28, dimension: 'communication', direction: 'them', text: 'En friend enga conversations-la details remember pannuvanga' },
    { id: 29, dimension: 'communication', direction: 'me', text: 'Naan en friend sollara important vishayam remember pannuven' },
    { id: 30, dimension: 'communication', direction: 'them', text: 'Communication natural-a easy-a irukkum' },

    // Emotional Support (15 questions)
    { id: 31, dimension: 'support', direction: 'them', text: 'Kashtamaana time-la en friend kooda irupanga' },
    { id: 32, dimension: 'support', direction: 'me', text: 'En friend struggle pannumbodhellam naan support kudukkuren' },
    { id: 33, dimension: 'support', direction: 'them', text: 'En friend en feelings-a validate pannuvanga' },
    { id: 34, dimension: 'support', direction: 'me', text: 'Naan en friend-oda emotions-a acknowledge pannuven' },
    { id: 35, dimension: 'support', direction: 'them', text: 'En friend en success-a celebrate pannuvanga' },
    { id: 36, dimension: 'support', direction: 'me', text: 'Naan en friend-oda achievements-a genuinely celebrate pannuven' },
    { id: 37, dimension: 'support', direction: 'them', text: 'Naan upset-a irukumbodhellam en friend comfort kudukkuvanga' },
    { id: 38, dimension: 'support', direction: 'me', text: 'Naan en friend-kku emotional comfort kudukkuren' },
    { id: 39, dimension: 'support', direction: 'them', text: 'Challenges-la en friend encourage pannuvanga' },
    { id: 40, dimension: 'support', direction: 'me', text: 'Naan en friend-a motivate pannuren encourage pannuren' },
    { id: 41, dimension: 'support', direction: 'them', text: 'En friend en struggles-kku empathy kaattuvanga' },
    { id: 42, dimension: 'support', direction: 'me', text: 'Naan en friend-oda difficulties-kku empathize pannuven' },
    { id: 43, dimension: 'support', direction: 'them', text: 'En friend regularly check-in pannuvanga' },
    { id: 44, dimension: 'support', direction: 'me', text: 'Naan en friend epdi irukkanga-nu reach out pannuven' },
    { id: 45, dimension: 'support', direction: 'them', text: 'En friend kooda emotionally safe-a feel pannuren' },

    // Mutual Respect (15 questions)
    { id: 46, dimension: 'respect', direction: 'them', text: 'Disagree pannalum en friend en opinions-a respect pannuvanga' },
    { id: 47, dimension: 'respect', direction: 'me', text: 'Different-a irundhaalum en friend-oda viewpoints-a respect pannuven' },
    { id: 48, dimension: 'respect', direction: 'them', text: 'En friend en time-a value pannuvanga' },
    { id: 49, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda schedule commitments-kku considerate-a iruken' },
    { id: 50, dimension: 'respect', direction: 'them', text: 'En friend enna accept pannuvanga as I am' },
    { id: 51, dimension: 'respect', direction: 'me', text: 'Naan en friend-a change panna try pannala accept pannuven' },
    { id: 52, dimension: 'respect', direction: 'them', text: 'En friend en life choices-a respect pannuvanga' },
    { id: 53, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda decisions life path-a support pannuven' },
    { id: 54, dimension: 'respect', direction: 'them', text: 'En friend enna belittle mock panna maatanga' },
    { id: 55, dimension: 'respect', direction: 'me', text: 'Naan en friend-a hurtful-a fun panna avoid pannuven' },
    { id: 56, dimension: 'respect', direction: 'them', text: 'En friend enna equal-a treat pannuvanga' },
    { id: 57, dimension: 'respect', direction: 'me', text: 'Naan en friend-a equal partner-a treat pannuven' },
    { id: 58, dimension: 'respect', direction: 'them', text: 'En friend en privacy-a respect pannuvanga' },
    { id: 59, dimension: 'respect', direction: 'me', text: 'Naan en friend-oda privacy need-a respect pannuven' },
    { id: 60, dimension: 'respect', direction: 'them', text: 'Naan valued appreciated-a feel pannuren' },

    // Boundaries (15 questions)
    { id: 61, dimension: 'boundaries', direction: 'them', text: 'En friend en boundaries-a respect pannuvanga' },
    { id: 62, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-oda boundaries-a honor pannuven' },
    { id: 63, dimension: 'boundaries', direction: 'them', text: 'En friend uncomfortable vishayam panna pressure pannala' },
    { id: 64, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-a comfort zone-kku mela push pannala' },
    { id: 65, dimension: 'boundaries', direction: 'them', text: 'Space venumna en friend understand pannuvanga' },
    { id: 66, dimension: 'boundaries', direction: 'me', text: 'En friend-kku space venum-na kudukkuren' },
    { id: 67, dimension: 'boundaries', direction: 'them', text: 'En friend en "no"-va guilt-trip illama accept pannuvanga' },
    { id: 68, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-oda "no"-va gracefully accept pannuven' },
    { id: 69, dimension: 'boundaries', direction: 'them', text: 'En friend excessive demands pannala' },
    { id: 70, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-a demands-naal overwhelm pannala' },
    { id: 71, dimension: 'boundaries', direction: 'them', text: 'En friend en other relationships-a respect pannuvanga' },
    { id: 72, dimension: 'boundaries', direction: 'me', text: 'Naan en friend-kku other friendships irukkuradha support pannuven' },
    { id: 73, dimension: 'boundaries', direction: 'them', text: 'En friend avanga boundaries clear-a communicate pannuvanga' },
    { id: 74, dimension: 'boundaries', direction: 'me', text: 'Naan en boundaries-a en friend-kitta clear-a express pannuven' },
    { id: 75, dimension: 'boundaries', direction: 'them', text: 'Friendship balanced-a irukkum one-sided illai' },

    // Personal Growth (15 questions)
    { id: 76, dimension: 'growth', direction: 'them', text: 'En friend en personal development-a encourage pannuvanga' },
    { id: 77, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda growth aspirations-a support pannuven' },
    { id: 78, dimension: 'growth', direction: 'them', text: 'En friend enna better-a irukka challenge pannuvanga (positive-a)' },
    { id: 79, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda potential reach panna help pannuven' },
    { id: 80, dimension: 'growth', direction: 'them', text: 'En success pathi en friend threatened feel pannala' },
    { id: 81, dimension: 'growth', direction: 'me', text: 'En friend-oda achievements pathi genuinely happy-a iruken' },
    { id: 82, dimension: 'growth', direction: 'them', text: 'En friend enna en goals pursue panna inspire pannuvanga' },
    { id: 83, dimension: 'growth', direction: 'me', text: 'Naan en friend-a dreams chase panna encourage pannuven' },
    { id: 84, dimension: 'growth', direction: 'them', text: 'Naan ketta en friend constructive feedback kudukkuvanga' },
    { id: 85, dimension: 'growth', direction: 'me', text: 'En friend kekkum-bodhu helpful advice kudukkuren' },
    { id: 86, dimension: 'growth', direction: 'them', text: 'En friend en mistakes-lerndhu learn panna help pannuvanga' },
    { id: 87, dimension: 'growth', direction: 'me', text: 'Naan en friend-a challenges-lerndhu learn grow panna help pannuven' },
    { id: 88, dimension: 'growth', direction: 'them', text: 'Indha friendship nala naan person-a grow pannirken' },
    { id: 89, dimension: 'growth', direction: 'me', text: 'Naan en friend-oda development-kku positive-a contribute pannuren' },
    { id: 90, dimension: 'growth', direction: 'them', text: 'En friend pudhusa try pannuradha support pannuvanga' },

    // Fun & Enjoyment (15 questions)
    { id: 91, dimension: 'fun', direction: 'them', text: 'En friend kooda time spend pannuradhu genuinely enjoy pannuren' },
    { id: 92, dimension: 'fun', direction: 'me', text: 'En friend en company-a enjoy pannuranganu theriyum' },
    { id: 93, dimension: 'fun', direction: 'them', text: 'En friend enna sirikkavechuva' },
    { id: 94, dimension: 'fun', direction: 'me', text: 'Naan en friend-kku joy laughter kudukkuren' },
    { id: 95, dimension: 'fun', direction: 'them', text: 'En friend kooda irukumbodhellam time seekiram poirum' },
    { id: 96, dimension: 'fun', direction: 'me', text: 'Naanum en friend-um fun memories create pannurom' },
    { id: 97, dimension: 'fun', direction: 'them', text: 'En friend plans initiate pannuvanga' },
    { id: 98, dimension: 'fun', direction: 'me', text: 'Naan quality time-kku effort pannuren' },
    { id: 99, dimension: 'fun', direction: 'them', text: 'En friend en sense of humor share pannuvanga' },
    { id: 100, dimension: 'fun', direction: 'me', text: 'Naan en friend-oda personality quirks-a appreciate pannuren' },
    { id: 101, dimension: 'fun', direction: 'them', text: 'En friend enna pudhusa experiences-kku introduce pannuvanga' },
    { id: 102, dimension: 'fun', direction: 'me', text: 'Naan interesting activities share pannuren' },
    { id: 103, dimension: 'fun', direction: 'them', text: 'En friend kooda irundhaa en stress reduce aaum' },
    { id: 104, dimension: 'fun', direction: 'me', text: 'En friend ennoda comfortable relaxed-a irupanga' },
    { id: 105, dimension: 'fun', direction: 'them', text: 'Naan en friend-a paakka look forward pannuren' },

    // Conflict Resolution (15 questions)
    { id: 106, dimension: 'conflict', direction: 'them', text: 'En friend issues-a avoid pannama directly address pannuvanga' },
    { id: 107, dimension: 'conflict', direction: 'me', text: 'Naan problems-a fester aaga vidama communicate pannuven' },
    { id: 108, dimension: 'conflict', direction: 'them', text: 'Disagreements-la en friend calm-a irupanga' },
    { id: 109, dimension: 'conflict', direction: 'me', text: 'Conflict-la kooda respectful-a iruken' },
    { id: 110, dimension: 'conflict', direction: 'them', text: 'Wrong-a irundha en friend sincerely apologize pannuvanga' },
    { id: 111, dimension: 'conflict', direction: 'me', text: 'Mistakes pannumbodhellam genuine apologies kudukkuren' },
    { id: 112, dimension: 'conflict', direction: 'them', text: 'En friend compromise panna willing-a irupanga' },
    { id: 113, dimension: 'conflict', direction: 'me', text: 'Disagreements-la middle ground paakkuren' },
    { id: 114, dimension: 'conflict', direction: 'them', text: 'Conflicts-kku piragu en friend forgive move forward pannuvanga' },
    { id: 115, dimension: 'conflict', direction: 'me', text: 'Naan grudges vidu en friend-a forgive pannuven' },
    { id: 116, dimension: 'conflict', direction: 'them', text: 'En friend past mistakes-a repeatedly bring up pannala' },
    { id: 117, dimension: 'conflict', direction: 'me', text: 'Naan past issues hold pannala' },
    { id: 118, dimension: 'conflict', direction: 'them', text: 'Conflicts-la en friend en perspective-a purinjukka try pannuvanga' },
    { id: 119, dimension: 'conflict', direction: 'me', text: 'Naan en friend-oda viewpoint-a paakka effort pannuven' },
    { id: 120, dimension: 'conflict', direction: 'them', text: 'Conflicts-a constructively resolve pannurom' },

    // Loyalty (15 questions)
    { id: 121, dimension: 'loyalty', direction: 'them', text: 'Yaaraachum criticize pannaa en friend ennakku stand up pannuvanga' },
    { id: 122, dimension: 'loyalty', direction: 'me', text: 'En friend illa-ppa naan defend pannuren' },
    { id: 123, dimension: 'loyalty', direction: 'them', text: 'En friend enga friendship-a prioritize pannuvanga' },
    { id: 124, dimension: 'loyalty', direction: 'me', text: 'Naan enga friendship-a en life-la priority-a vaikkuren' },
    { id: 125, dimension: 'loyalty', direction: 'them', text: 'En friend consistent-a irupanga' },
    { id: 126, dimension: 'loyalty', direction: 'me', text: 'Naan dependable consistent-a iruken' },
    { id: 127, dimension: 'loyalty', direction: 'them', text: 'Tough times-la en friend abandon pannala' },
    { id: 128, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-oda challenges-la stick pannuren' },
    { id: 129, dimension: 'loyalty', direction: 'them', text: 'En friend enna avanga life-la include pannuvanga' },
    { id: 130, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-a en life-la include panna effort pannuren' },
    { id: 131, dimension: 'loyalty', direction: 'them', text: 'En friend last minute-la plans cancel pannala (emergency-a illama)' },
    { id: 132, dimension: 'loyalty', direction: 'me', text: 'Naan en commitments-a honor pannuren' },
    { id: 133, dimension: 'loyalty', direction: 'them', text: 'En friend en back-a paathupa' },
    { id: 134, dimension: 'loyalty', direction: 'me', text: 'Naan en friend-a unconditionally support pannuren' },
    { id: 135, dimension: 'loyalty', direction: 'them', text: 'En friend-a long-term count panna mudiyum' },

    // Authenticity (15 questions)
    { id: 136, dimension: 'authenticity', direction: 'them', text: 'En friend genuine authentic-a irupanga' },
    { id: 137, dimension: 'authenticity', direction: 'me', text: 'En friend kooda true self-a irukkamudiyum' },
    { id: 138, dimension: 'authenticity', direction: 'them', text: 'En friend real thoughts feelings share pannuvanga' },
    { id: 139, dimension: 'authenticity', direction: 'me', text: 'Indha friendship-la naan authentic-a express pannuren' },
    { id: 140, dimension: 'authenticity', direction: 'them', text: 'En friend yaarodha pretend pannala' },
    { id: 141, dimension: 'authenticity', direction: 'me', text: 'En friend kooda mask wear pannanum-nu thonadhilla' },
    { id: 142, dimension: 'authenticity', direction: 'them', text: 'En friend avanga vulnerabilities admit pannuvanga' },
    { id: 143, dimension: 'authenticity', direction: 'me', text: 'En vulnerable side-a kaatturadhu safe-a feel pannuren' },
    { id: 144, dimension: 'authenticity', direction: 'them', text: 'En friend-oda words actions match aaum' },
    { id: 145, dimension: 'authenticity', direction: 'me', text: 'Naan solluradha practice pannuren' },
    { id: 146, dimension: 'authenticity', direction: 'them', text: 'En friend games aadala manipulate pannala' },
    { id: 147, dimension: 'authenticity', direction: 'me', text: 'Naan straightforward honest-a iruken' },
    { id: 148, dimension: 'authenticity', direction: 'them', text: 'En friend-oda intentions genuine-nu trust pannuren' },
    { id: 149, dimension: 'authenticity', direction: 'me', text: 'En friend-kku best interests-la trust pandranga' },
    { id: 150, dimension: 'authenticity', direction: 'them', text: 'Indha friendship real meaningful-a irukkum' },
  ]
};

export const SCORE_CATEGORIES = [
  { min: 85, max: 100, label: 'Thriving Friendship', color: '#10b981', emoji: '🌟' },
  { min: 70, max: 84, label: 'Healthy Friendship', color: '#3b82f6', emoji: '💙' },
  { min: 55, max: 69, label: 'Moderate Friendship', color: '#eab308', emoji: '⚡' },
  { min: 40, max: 54, label: 'Struggling Friendship', color: '#f97316', emoji: '⚠️' },
  { min: 0, max: 39, label: 'Unhealthy Friendship', color: '#ef4444', emoji: '🚨' }
];

export const getScoreCategory = (score) => {
  return SCORE_CATEGORIES.find(cat => score >= cat.min && score <= cat.max) || SCORE_CATEGORIES[4];
};
